// Code generated by protoc-gen-go-aip. DO NOT EDIT.
//
// versions:
// 	protoc-gen-go-aip development
// 	protoc (unknown)
// source: rest/proto/vnprovince.proto

package proto

import (
	fmt "fmt"
	strings "strings"

	resourcename "go.einride.tech/aip/resourcename"
)

type DivisionResourceName struct {
	DivisionId string
}

func (n DivisionResourceName) Validate() error {
	if n.DivisionId == "" {
		return fmt.Errorf("division_id: empty")
	}
	if strings.IndexByte(n.DivisionId, '/') != -1 {
		return fmt.Errorf("division_id: contains illegal character '/'")
	}
	return nil
}

func (n DivisionResourceName) ContainsWildcard() bool {
	return false || n.DivisionId == "-"
}

func (n DivisionResourceName) String() string {
	return resourcename.Sprint(
		"divisions/{division_id}",
		n.DivisionId,
	)
}

func (n DivisionResourceName) MarshalString() (string, error) {
	if err := n.Validate(); err != nil {
		return "", err
	}
	return n.String(), nil
}

func (n *DivisionResourceName) UnmarshalString(name string) error {
	return resourcename.Sscan(
		name,
		"divisions/{division_id}",
		&n.DivisionId,
	)
}
